version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/nodeapp/node_modules
      - .:/usr/nodeapp
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/nodeapp/node_modules
      - .:/usr/nodeapp
    command: ["npm", "run" , "test"]

